SELECT 
    ROW_NUMBER() OVER(ORDER BY PRD.PRODUCT_ID) AS PRODUCT_KEY,
    PRD.PRODUCT_ID,
    PRD.PRODUCT_NAME,
    CAT.CATEGORY_NAME,
    BR.BRAND_NAME,
    PRD.MODEL_YEAR,
    PRD.LIST_PRICE AS UNIT_PRICE


FROM {{ref('products')}} PRD
LEFT JOIN 
{{ref('categories')}} CAT
ON PRD.CATEGORY_ID = CAT.CATEGORY_ID
LEFT JOIN 
{{ref('brands')}} BR
ON PRD.BRAND_ID = BR.BRAND_ID
