SELECT 
    ROW_NUMBER() OVER (ORDER BY STAFF.STAFF_ID) AS STAFF_KEY,
    STAFF.STAFF_ID,
    STAFF.FULL_NAME,
    STAFF.EMAIL,
    STAFF.ACTIVE AS IS_ACTIVE,
    STORE.STORE_NAME,
    STAFF.MANAGER_ID

FROM {{ref('staffs')}} STAFF
LEFT JOIN 
{{ref('stores')}} STORE
ON STAFF.STORE_ID=STORE.STORE_ID
