COPY INTO BRONZE.CUSTOMERS
FROM @EXTER_STG/customers/
ON_ERROR = 'CONTINUE';

COPY INTO BRONZE.ORDERS
FROM @EXTER_STG/orders/
ON_ERROR = 'CONTINUE';

COPY INTO BRONZE.ORDER_ITEMS
FROM @EXTER_STG/order_items/
ON_ERROR = 'CONTINUE';

COPY INTO BRONZE.PRODUCTS
FROM @EXTER_STG/products/
ON_ERROR = 'CONTINUE';

COPY INTO BRONZE.CATEGORIES
FROM @EXTER_STG/categories/
ON_ERROR = 'CONTINUE';

COPY INTO BRONZE.BRANDS
FROM @EXTER_STG/brands/
ON_ERROR = 'CONTINUE';

COPY INTO BRONZE.STORES
FROM @EXTER_STG/stores/
ON_ERROR = 'CONTINUE';

COPY INTO BRONZE.STAFFS
FROM @EXTER_STG/staffs/
ON_ERROR = 'CONTINUE';

COPY INTO BRONZE.STOCKS
FROM @EXTER_STG/stocks/
ON_ERROR = 'CONTINUE'; 
