CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1;

CREATE OR REPLACE STORAGE INTEGRATION SALES_DB_S3_INTEG
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED  = TRUE
STORAGE_AWS_ROLE_ARN='arn:aws:iam::551569010870:role/SnowflakeSalesOLAPRole'
STORAGE_ALLOWED_LOCATIONS=('s3://sales-database-files/');