USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    PHONE VARCHAR,
    EMAIL VARCHAR,
    STREET VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    ZIP_CODE VARCHAR
);

CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    ORDER_STATUS VARCHAR,
    ORDER_DATE VARCHAR,
    REQUIRED_DATE VARCHAR,
    SHIPPED_DATE VARCHAR,
    STORE_ID VARCHAR,
    STAFF_ID VARCHAR
);

CREATE OR REPLACE TABLE ORDER_ITEMS (
    ORDER_ID VARCHAR,
    ITEM_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    QUANTITY VARCHAR,
    LIST_PRICE VARCHAR,
    DISCOUNT VARCHAR
);

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    BRAND_ID VARCHAR,
    CATEGORY_ID VARCHAR,
    MODEL_YEAR VARCHAR,
    LIST_PRICE VARCHAR
);

CREATE OR REPLACE TABLE CATEGORIES (
    CATEGORY_ID VARCHAR,
    CATEGORY_NAME VARCHAR
);


CREATE OR REPLACE TABLE BRANDS (
    BRAND_ID VARCHAR,
    BRAND_NAME VARCHAR
);

CREATE OR REPLACE TABLE STORES (
    STORE_ID VARCHAR,
    STORE_NAME VARCHAR,
    PHONE VARCHAR,
    EMAIL VARCHAR,
    STREET VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    ZIP_CODE VARCHAR
);


CREATE OR REPLACE TABLE STAFFS (
    STAFF_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    ACTIVE VARCHAR,
    STORE_ID VARCHAR,
    MANAGER_ID VARCHAR
);