SELECT 
    ROW_NUMBER() OVER(ORDER BY O.ORDER_ID) AS SALES_KEY,
    O.ORDER_ID AS ORDER_ID,
    DC.CUSTOMER_KEY AS CUSTOMER_KEY,
    DSF.STAFF_KEY AS STAFF_KEY,
    DSR.STORE_KEY AS STORE_KEY,
    DP.PRODUCT_KEY AS PRODUCT_KEY,
    ODD.DATE_KEY AS ORDER_DATE_KEY,
    RDD.DATE_KEY AS REQUIRED_DATE_KEY,
    SDD.DATE_KEY AS SHIPPED_DATE_KEY,
    OI.QUANTITY AS QUANTITY,
    OI.LIST_PRICE AS UNIT_PRICE,
    (OI.QUANTITY * OI.LIST_PRICE * (1 - OI.DISCOUNT)) AS SALES_AMOUNT,
    OI.DISCOUNT AS DISCOUNT


FROM {{ref('orders')}} O
JOIN
 {{ref('order_items')}} OI
ON O.ORDER_ID = OI.ORDER_ID
JOIN
 {{ref('dim_customers')}} DC
ON O.CUSTOMER_ID = DC.CUSTOMER_ID
JOIN
 {{ref('dim_staffs')}} DSF
ON O.STAFF_ID = DSF.STAFF_ID
JOIN
 {{ref('dim_stores')}} DSR
ON O.STORE_ID = DSR.STORE_ID
JOIN
 {{ref('dim_products')}} DP
ON OI.PRODUCT_ID = DP.PRODUCT_ID
JOIN
 {{ref('dim_date')}} ODD
ON O.ORDER_DATE = ODD.FULL_DATE
JOIN 
 {{ref('dim_date')}} RDD
ON O.REQUIRED_DATE = RDD.FULL_DATE
JOIN
 {{ref('dim_date')}} SDD
ON O.SHIPPED_DATE = SDD.FULL_DATE






