SELECT 
    ROW_NUMBER()OVER(ORDER BY S.STORE_ID, S.PRODUCT_ID) AS INVENTORY_KEY,
    DS.STORE_KEY AS STORE_KEY,
    DP.PRODUCT_KEY AS PRODUCT_KEY,
    S.QUANTITY AS STOCK_QUANTITY

FROM {{ref('stocks')}} S
JOIN
  {{ref('dim_stores')}} DS
ON S.STORE_ID = DS.STORE_ID
JOIN
  {{ref('dim_products')}} DP
ON S.PRODUCT_ID = DP.PRODUCT_ID
