SELECT DISTINCT
    TRY_TO_NUMBER(TRIM(customer_id)) AS CUSTOMER_ID,
    CONCAT(TRIM(COALESCE(FIRST_NAME, '')), ' ',TRIM(COALESCE(LAST_NAME, ''))) AS FULL_NAME,
    COALESCE(LOWER(TRIM(EMAIL)), 'unknown@example.com') AS EMAIL,
    TRIM(COALESCE(STREET, 'UNKNOWN')) AS STREET,
    TRIM(COALESCE(CITY, 'UNKNOWN')) AS CITY,
    UPPER(TRIM(COALESCE(STATE, 'UNKNOWN'))) AS STATE,
    TRIM(COALESCE(ZIP_CODE, 'UNKNOWN')) AS ZIP_CODE

FROM {{source('bronze', 'CUSTOMERS')}}
    