SELECT DISTINCT
    TRY_TO_NUMBER(TRIM(ORDER_ID)) AS ORDER_ID,
    TRY_TO_NUMBER(TRIM(CUSTOMER_ID)) AS CUSTOMER_ID,
    TRY_TO_NUMBER(TRIM(ORDER_STATUS)) AS ORDER_STATUS,
    TRY_TO_DATE(
        CASE
            WHEN SUBSTRING(TRIM(ORDER_DATE),1,2) = '10'
                THEN CONCAT('20', SUBSTRING(TRIM(ORDER_DATE),3))
            ELSE TRIM(ORDER_DATE)
        END
    ) AS ORDER_DATE,

    TRY_TO_DATE(
    CASE 
        WHEN SUBSTRING(TRIM(REQUIRED_DATE),1,2) = '10'
         THEN CONCAT('20', SUBSTRING(TRIM(REQUIRED_DATE), 3, 8))
         ELSE REQUIRED_DATE
    END  ) AS REQUIRED_DATE,

    TRY_TO_DATE(
    CASE 
        WHEN SUBSTRING(TRIM(SHIPPED_DATE),1,2) = '10'
         THEN CONCAT('20', SUBSTRING(TRIM(SHIPPED_DATE), 3, 8))
         ELSE SHIPPED_DATE
    END ) AS SHIPPED_DATE,
    TRY_TO_NUMBER(TRIM(STORE_ID)) AS STORE_ID,
    TRY_TO_NUMBER(TRIM(STAFF_ID)) AS STAFF_ID
FROM {{ source('bronze', 'ORDERS') }}
    
    


    