SELECT DISTINCT
    TRY_TO_NUMBER(TRIM(ORDER_ID)) AS ORDER_ID,
    TRY_TO_NUMBER(TRIM(ITEM_ID)) AS ITEM_ID,
    TRY_TO_NUMBER(TRIM(PRODUCT_ID)) AS PRODUCT_ID,
    TRY_TO_NUMBER(TRIM(QUANTITY)) AS QUANTITY,
    TRY_TO_DECIMAL(TRIM(LIST_PRICE), 10, 2) AS LIST_PRICE, 
    TRY_TO_DECIMAL(TRIM(DISCOUNT), 10, 2) AS DISCOUNT
FROM {{source('bronze', 'ORDER_ITEMS')}}