SELECT  DISTINCT

    TRY_TO_NUMBER(TRIM(PRODUCT_ID)) AS PRODUCT_ID,
    TRIM(COALESCE(PRODUCT_NAME, 'UNKNOWN')) AS PRODUCT_NAME,
    TRY_TO_NUMBER(TRIM(BRAND_ID)) AS BRAND_ID,
    TRY_TO_NUMBER(TRIM(CATEGORY_ID)) AS CATEGORY_ID,
    TRY_TO_NUMBER(TRIM(MODEL_YEAR)) AS MODEL_YEAR,
    TRY_TO_DECIMAL(TRIM(LIST_PRICE), 10, 2) AS LIST_PRICE

FROM {{source('bronze', 'PRODUCTS')}}