SELECT DISTINCT
    TRY_TO_NUMBER(TRIM(STAFF_ID)) AS STAFF_ID,
    CONCAT(TRIM(COALESCE(FIRST_NAME,'')), ' ',TRIM(COALESCE(LAST_NAME,''))) AS FULL_NAME,
    LOWER(TRIM(COALESCE(EMAIL,'unknown@example.com'))) AS EMAIL,
    TRY_TO_NUMBER(TRIM(COALESCE(ACTIVE, '2'))) AS ACTIVE, -- True = 1, False = 0, Unknown = 2
    TRY_TO_NUMBER(TRIM(STORE_ID)) AS STORE_ID,-- 0 MEANS UNKNOWN
    TRY_TO_NUMBER(TRIM(MANAGER_ID)) AS MANAGER_ID -- 0 MEANS UNKNOWN
FROM {{source('bronze', 'STAFFS')}}