SELECT DISTINCT
    TRY_TO_NUMBER(TRIM(STORE_ID)) AS STORE_ID,
    TRY_TO_NUMBER(TRIM(PRODUCT_ID)) AS PRODUCT_ID,
    TRY_TO_NUMBER(TRIM(COALESCE(QUANTITY, '0'))) AS QUANTITY
FROM {{source('bronze', 'STOCKS')}}