SELECT DISTINCT 
    TRY_TO_NUMBER(TRIM(STORE_ID)) AS STORE_ID,
    TRIM(COALESCE(STORE_NAME, 'UNKNOWN')) AS STORE_NAME,
    LOWER(TRIM(COALESCE(EMAIL, 'unknown@example.com'))) AS EMAIL,
    TRIM(COALESCE(STREET, 'UNKNOWN')) AS STREET,
    TRIM(COALESCE(CITY, 'UNKNOWN')) AS CITY,
    UPPER(TRIM(COALESCE(STATE, 'UNKNOWN'))) AS STATE,
    TRIM(COALESCE(ZIP_CODE, 'UNKNOWN')) AS ZIP_CODE,
    TRIM(COALESCE(PHONE,'UNKNOWN')) AS PHONE
FROM {{source('bronze', 'STORES')}}